# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SISO application
email: roy.kokkelkoren@xsec.nl
description: > # this means to ignore newlines until "baseurl:"
  SISO is a simple and secure file transfer system. It provides 
  functionality to send confidential files securely and easily
  over the internet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  rkokkelk

# Build settings
markdown: kramdown
