# SISO configuration file
# Please restart the application after changing this file

defaults: &defaults

  #############
  # General
  #############

  # IP-range from which user allowed to create repositories
  # Specify using a comma separated value in CIDR format.
  # e.g 192.168.0.0/24, 127.0.0.1/24, 144.212.233.1/32
  IP_WHITE_LIST: 0.0.0.0/0

  # Set Language, default is set to English
  # Options: en nl
  LOCALE: en

  #############
  # Logging
  #############

  # Specify how to log messages from SISO
  # File is written to log directory
  # Options: stdout file
  LOGGER: stdout

  # Set log level
  # Options: debug info warn error fatal
  LOG_LEVEL: info

  #############
  # Security
  #############

  # Set minimum amount of entropy required for a password to be accepted.
  # See more info at: https://cubicspot.blogspot.nl/2011/11/how-to-calculate-password-strength.html
  MIN_ENTROPY_PW: 10

  # Number of rounds used for the Password-Based Key Derivation Function, increasing this number will
  # increase the security of the master key. Do not alter if you are unfamiliar with the subject
  # IMPORTANT: altering this number will make it impossible to login in existing repositories
  PBKDF_ROUNDS: 20_000

#
# Do not modify the following lines
#
production:
  <<: *defaults

heroku:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

