# SISO configuration file
#
# Please restart the application after changing this file

# IP-range from which user allowed to create repositories
# Specify using a comma separated value in CIDR format.
# e.g 192.168.0.0/24, 127.0.0.1/24, 144.212.233.1/32
IP_WHITE_LIST: 0.0.0.0/0

# Set Language, default is set to English
# Possible settings: en nl
LOCALE: nl