# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63f79703f2ebb051362f71c09e3bb24c394c011509cae0ca3bdf4bd172de52287288b0817ab6e3b7b2da45a3724fa4178c04bdad6dc4e67c497e09a5f0156136

test:
  secret_key_base: 69a3cd6685a6af643fd624d172affd285fdfdb35e182133360ee04fcd218e071090107328cdf1b357b7184ec66b03f85a205a5de86f4baed39a033e96bef938d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

heroku:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>